# –§–∞–π–ª –æ–±—â–µ–π –∫–æ–Ω—Ñ–∏–≥—É—Ä–∞—Ü–∏–∏ —Å–∞–π—Ç–∞
name = "–°—ç–º –ë—É–ª–∞—Ç–æ–≤"
description = "–ü—Ä–∏–≤–µ—Ç üëã. –Ø –°—ç–º —Ñ—Ä–æ–Ω—Ç–µ–Ω–¥ —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫ –∏ –≤ —ç—Ç–æ–º –±–ª–æ–≥–µ —è —Ä–∞—Å—Å–∫–∞–∑—ã–≤–∞—é –æ —Å–≤–æ–µ–º –æ–ø—ã—Ç–µ"

accentColor = "#8870ff"
url = "https://mephi.dev"
feedUrl = "https://mephi.dev/feed.xml"

[author]
name = "–°—ç–º –ë—É–ª–∞—Ç–æ–≤"
email = "mephistorine@gmail.com"
twitter = "mephistorine"

[[menu]]
label = "–ü—Ä–æ–µ–∫—Ç—ã"
url = "/projects"

[[menu]]
label = "–î–æ–∫–ª–∞–¥—ã"
url = "/talks"

[[menu]]
label = "–û–±–æ –º–Ω–µ"
url = "/about"

[[menu]]
label = "–ö–æ–Ω—Ç–∞–∫—Ç—ã"
url = "/about#contacts"
